export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    ACCEPT_INVITE: '/auth/accept-invite',
    ME: '/auth/me',
    INVITES: '/auth/invites',
  },
  USERS: {
    LIST: '/users',
    DETAIL: (id: string) => `/users/${id}`,
  },
  LEADS: {
    LIST: '/leads',
    DETAIL: (id: string) => `/leads/${id}`,
    CREATE: '/leads',
    UPDATE: (id: string) => `/leads/${id}`,
    DELETE: (id: string) => `/leads/${id}`,
    MATCHES: (id: string) => `/leads/${id}/matches`,
    INTERACTIONS: (id: string) => `/leads/${id}/interactions`,
  },
  PROPERTIES: {
    LIST: '/properties',
    DETAIL: (id: string) => `/properties/${id}`,
    CREATE: '/properties',
    UPDATE: (id: string) => `/properties/${id}`,
    DELETE: (id: string) => `/properties/${id}`,
    UPLOAD_IMAGES: '/properties/upload-images',
    MATCHES: (id: string) => `/properties/${id}/matches`,
  },
  MATCHES: {
    LIST: '/matches',
    DETAIL: (id: string) => `/matches/${id}`,
    UPDATE_STATUS: (id: string) => `/matches/${id}/status`,
    CONFIG: '/matches/config',
    RECALCULATE_LEAD: (leadId: string) => `/matches/recalculate/lead/${leadId}`,
    RECALCULATE_PROPERTY: (propertyId: string) => `/matches/recalculate/property/${propertyId}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DISMISS: (id: string) => `/notifications/${id}`,
  },
  DASHBOARD: {
    OVERVIEW: '/dashboard',
    STATS: '/dashboard/stats',
    RECENT_LEADS: '/dashboard/recent-leads',
    AGING_INVENTORY: '/dashboard/aging-inventory',
  },
  SETTINGS: {
    GET: '/settings',
    UPDATE: '/settings',
  },
} as const;
